### ISSUE TITLE
DATA PAGE: Export to CSV not functional for Linux desktop

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#4]
# Description

On Linux desktop I get the following exception when I click Export to CSV

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method cancelAllTasks on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      Workmanager.cancelAll (package:workmanager/src/workmanager.dart:262:7)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: getExternalStoragePath() has not been implemented.
#0      PathProviderPlatform.getExternalStoragePath (package:path_provider_platform_interface/path_provider_platform_interface.dart:75:5)
#1      getExternalStorageDirectory (package:path_provider/path_provider.dart:154:40)
#2      _HomeDataState.exportToCsv (package:securedialog/ui/home_page/home_data.dart:132:29)
#3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333:11)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
#21     _invoke1 (dart:ui/hooks.dart:186:13)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)
```

This could be an issue with the package being used. Please ensure all packages support all platforms.

# Why

The application needs to be fully functional on all platforms.

# Closing Criteria

- [ ] Export to CSV works on linux desktop

**Comment by gjwgit** [comment]
getExternalStorage from path_provider only works on Android and so failing on every other platform. We need an alternative to this to be truely cross platform.

**Comment by kimishidairessha** [comment]
Replace 'share' with 'share_plus'
https://pub.dev/packages/share_plus

**Comment by kimishidairessha** [comment]
Test android, windows and web. All work well now. For web, downloading csv to the device. Replace getExternalStorage with getApplicationDocumentsDirectory which work on Android, iOS, Linux, macOS and Windows
.

**Comment by gjwgit** [comment]
I still get an exception on Linux:

```

**Comment by gjwgit** [comment]
Graham to check with team re best way to export data as CSV.

**Comment by gjwgit** [comment]
Propose you use file_picker for saving the files on non-kIsWeb as in indipod share_log_buttons.dart
