### ISSUE TITLE
BUG: After authentication on Linux get a missing plugin exception

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#42]

**Comment by gjwgit** [comment]
I seem to be getting it every time I go back to the app (lose focus get focus...)

```
flutter: App lifecycle state monitor: AppLifecycleState.resumed
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method cancelAllTasks on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      Workmanager.cancelAll (package:workmanager/src/workmanager.dart:262:7)
<asynchronous suspension>
#2      _HomeOSMState.didChangeAppLifecycleState.<anonymous closure> (package:securedialog/ui/home_page/home_osm.dart:326:40)
<asynchronous suspension>

flutter: App lifecycle state monitor: AppLifecycleState.inactive
flutter: App lifecycle state monitor: AppLifecycleState.resumed
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method cancelAllTasks on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      Workmanager.cancelAll (package:workmanager/src/workmanager.dart:262:7)
<asynchronous suspension>
#2      _HomeOSMState.didChangeAppLifecycleState.<anonymous closure> (package:securedialog/ui/home_page/home_osm.dart:326:40)
<asynchronous suspension>

flutter: App lifecycle state monitor: AppLifecycleState.inactive
```

**Comment by kimishidairessha** [comment]
It seems that the Workmanager plugin may have limited support for Linux. 'Workmanager' used in 'home_osm.dart'. The 'Workmanager' plugin in 'home_osm.dart' is used to manage background tasks, specifically for collecting and processing geographical data based on the app's lifecycle state changes.

**Comment by gjwgit** [comment]
According to https://pub.dev/packages/workmanager only support on ios and android. For all other platforms we need to conditionally ignore the functionality.

Or else is there a better replacement that supports all platforms.
